version: 2.1

orbs:
  codacy: codacy/base@10.11.1

references:
  cache_prefix: &cache_prefix sbt-cache-24012024

workflows:
  version: 2

  compile_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt_docker:
          name: test
          steps:
            - run:
                name: Compile tests
                command: sbt +test:compile
          cache_prefix: *cache_prefix
          setup_remote_docker: false
          context: CodacyAWS
          requires:
            - codacy/checkout_and_version
      - codacy/sbt_docker:
          name: publish
          steps:
            - run:
                name: Retrieve GPG keys
                command: sbt retrieveGPGKeys
            - run:
                name: Publish to bundle
                command: sbt +publishSigned
            - run:
                name: Release bundle to Sonatype
                command: sbt sonatypeBundleRelease
          cache_prefix: *cache_prefix
          context: CodacyAWS
          aws_profile: production
          use_sbt_native_client: false
          setup_remote_docker: false
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          context: CodacyAWS
          requires:
            - publish